name: Add metrics in personoal profile
on:
  push:
    branches: [ master ]

jobs:

  add_metrics_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}


          
